name: uoc20241pec1
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas=1.0.1
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - numpy=2.2.3
  - pandas=2.2.3
  - python=3.13.2
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - ucimlrepo=0.0.7